stages:
  - compile
  - test
  - deploy

building:
  tags:
    - docker
  stage: compile
  script:
    - javac -Djava.ext.dirs=library mdw2021/CompetitionMainClass.java

testing:
  tags:
    - docker
  stage: test
  script:
    - ./test.sh

bridge:
  tags:
    - docker
  stage: deploy
  script:
  - "curl -X POST -F token=ce90992025c2e7cafd0eb55f8312ec -F ref=main https://git-ce.rwth-aachen.de/api/v4/projects/8105/trigger/pipeline"
  #trigger:
  #  project: m2021/md2021global
